

source "https://rubygems.org"

gem "net-smtp", "~> 0.3"
gem "pony",     "~> 1.13"
gem "puma",     "~> 6.3"
gem "sinatra", "~> 3.1", ">= 3.1.0"

gem "opentelemetry-sdk", "~> 1.2"
gem "opentelemetry-exporter-otlp", "~> 0.25", ">= 0.25.0"
gem "opentelemetry-instrumentation-all", "~> 0.39"
